### ISSUE TITLE
Map Editor: Remove "Eye Candy" button

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#102]
The "eye candy" does not work, and I doubt it ever will at this point. I don't think it'll be of any benefit to make it work now either.

The button for it is confusing to those trying to learn the editor. Even I thought it was how particles were added at first before digging through the forum and learning how to actually do particles.

This button should be removed. Or I guess more appropriately, only show in an "#ifdef	EYE_CANDY" condition.

![eyecandybutton](https://user-images.githubusercontent.com/2794779/103475142-c46a1e00-4daa-11eb-9ae2-8da3a4c40135.jpg)

**Comment by gvissers** [comment]
Huh, not having worked with the map editor in possibly decades, I assumed this was actually how particle systems were added to the map, and that the fourth button was for "old-fashioned" particle systems only. The "old" particle systems are actually mapped to "new" particle systems in the client code.

I will probably have a look at this later, see if I can figure out what it's supposed to do.

**Comment by feeltheburn** [comment]
It's hosed, whatever it's supposed to do.

I've worked extensively on every non-guild map in the game over the past 5 or so years, between that and writing scripts that auto-generate maps and map debugging images, I can 100% say all particles on current maps are from what's found in the particles button.

The eye candy was supposed to do odd crap like wind blowing leaves, much more advanced than anything on any map. And would probably kill the android client if used, heh.

THE CLIENT CRASHES! If you put some eye candy on the map, like the aforementioned leaves. 

And oh yeah, there's serious issues with trying to delete an eye candy when placed. 

There's just nothing about it that screams "stable". I wouldn't accept any map to be put on the server that has this eye candy on it.

**Comment by gvissers** [comment]
Ok, the eye candy button should no longer show up if the editor is not compiled with EYE_CANDY defined.

**Comment by feeltheburn** [comment]
Works.

The Makefile.win and Makefile.linux files should probably be updated to not have EYE_CANDY compiled by default. Just a quick fix near the top of each file.

**Comment by gvissers** [comment]
Oh yeah, I mistakenly assumed that was the default. Corrected.
