### ISSUE TITLE
Map Editor: Ctrl-E 3D panel doesn't understand blended 20 = deleted

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#112]
Reproduce:

1) Press 3D button. Ctrl-B. Grab any 3d object and place it on the map.

2) Press Ctrl-E to open the object details panel, initially blank. Click the object while holding alt to show that object's info.

3) With that info panel still open, delete the object. You'll see the "Blended" info change to Yes.

4) PROBLEMATIC: Click the **+** next to Blended on the panel to change it to No. **The deleted object reappears.** Click the + again and it'll just be "blended", not gone.

I guess this is a very awkward way to be able to undo an object deletion, but it doesn't present itself that way and it would only work if the object's info was alt-clicked into the detail panel first.

I get how this would happen since blended = 20 is used to delete an object, but I would recommend: 

- Empty the detail panel of all information when the object is deleted, so it is blank just like when it's first opened with Ctrl-E.

**Comment by gvissers** [comment]
Should be fixed

**Comment by gvissers** [comment]
I believe this issue is fixed, so I'm closing it. @feeltheburn , if you disagree, please reopen.
