### ISSUE TITLE
Block repeating of You need to equip a quiver first!

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#127]
"You need to equip a quiver first!"

There's already a system in place to block constant repeating of the same message, so was wondering if this message could get blocked as well. It shows up as red spam if you're wearing a bow but no arrow.

(In the arenas, even when watching using the allowed autoclicker there, you end up with a flood of this message when the arrows run out before you can shut down the autoclicking. Very quickly hides any chats being viewed by throwing them off the screen.)

**Comment by gvissers** [comment]
Closed by accident.

I have tried to fix this in c315bfe, but haven't been able to test it due to lack of a bow. If it works, feel free to close the issue, otherwise, please reply here.

**Comment by feeltheburn** [comment]
Seems to work fine, thx.
