### ISSUE TITLE
Side Text on Tab Map View shouldn't use Mapmark Text Size

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#138]
This text shown in the bottom left of the tab map view changes size dependent on the mapmark text size.

I don't understand this. The mapmark text size gets changed to make it be less in the way, and most marks people already know why they marked it, they just need the mark there. So I tend to want to shrink it to where it's barely legible.

That, however, makes trying to view coordinates on the left difficult to read as well, and it makes no sense as that area the text is in doesn't change size.

Can we not have the size of that text attached to the mapmark size?

![extratext](https://user-images.githubusercontent.com/2794779/125433970-8352952d-a3bc-43e3-99a7-2c4e7c0f97d4.jpg)

**Comment by gvissers** [comment]
You're right, that doesn't make sense. Should be fixed in 7fe7b150.

**Comment by feeltheburn** [comment]
Tests good, thx
