### ISSUE TITLE
Tab Map should remain the same size in F6 mode

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#139]
http://www.eternal-lands.com/forum/index.php?/topic/61590-map-size-with-f6-active

The tab map view should stay the same size even in F6 mode, since good chunks of the map end up under parts of the interface and can't be clicked, which renders the F6 option annoying or even useless for those that want it.

**Comment by gvissers** [comment]
Cool, I didn't even know we _had_ an F6 mode. I don't think it has a proper name yet, either :laughing: 

Should be fixed in  c256cc8b.

**Comment by feeltheburn** [comment]
Tests good, thx
