### ISSUE TITLE
Downloading new (official) custom clothes goes wonky when starting multiple clients

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#142]
Not that big a deal, but if the custom_clothes.zip file needs to be downloaded (it's been updated) on initial client start, and you open multiple clients at once, the zip file somehow just gets deleted after it finishes all the downloads.

**REPRODUCE:** This can be tested by closing clients, deleting the ~/.elc/custom_clothes.zip (linux loc), then opening two clients at the same time. The battle to download it between them somehow results in it just being deleted.

(if you don't have that zip file, maybe check to see if Server -> Custom Looks Updates is marked.)

**Comment by gvissers** [comment]
I don't know how the file gets lost, but I can see how multiple clients can thread on each other's toes since they use the same temporary file names. We should probably use mkstemp() or tmpfile() instead so that update file names are unique. I can have a look tomorrow.

**Comment by gvissers** [comment]
Should be fixed with 91ee2ff

**Comment by feeltheburn** [comment]
This seems to be fixed from a few initial test, so I'll close, thanks.
