### ISSUE TITLE
Contrast of overhead mana

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#148]
The brightness of the green health and the darkness of the blue mana pretty much guarantee no situation where both are easily legible, even with the alpha behind them.

I'm recommending the blue of the mana be brighter so it's more easily legible with the same background as the green health. This would also make it more easily read with the alpha background.

![contrast](https://user-images.githubusercontent.com/2794779/130427302-9a3bb375-1004-4532-8dd7-c718807f7a60.png)

**Comment by pjbroad** [comment]
Agreed.  I'll also add the colours to the configurable named colours while I'm at it.  Do you have a suggestion for the default?

**Comment by feeltheburn** [comment]
Slightly brighter blue might be better, but as-is it seems servicable, thanks. I'll close, re-open if it seems to be problematic still after a few invances or such.
