### ISSUE TITLE
EL client crashed when a few people summoned a lot of things in WS city castle

### ISSUE THREAD

**Issue by hussamT** [raduprv/Eternal-Lands#15]
systemd logged this:  
         PID: 4562 (el.x86.linux.bi)
           UID: 1000 (hussam)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sun 2014-10-26 21:24:09 EET (1min 28s ago)
  Command Line: ./el.x86.linux.bin
    Executable: /home/hussam/games/el_linux/el.x86.linux.bin
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (hussam)
       Boot ID: 1c708dbd83b2416483c54d41c37175dd
    Machine ID: efb490e643e2436d9d1138df1745a008
      Hostname: hades
       Message: Process 4562 (el.x86.linux.bi) of user 1000 dumped core.
                
                Stack trace of thread 4562:
                #0  0x000000000041ef33 add_command_to_actor (el.x86.linux.bin)
                #1  0x00000000004e7948 process_message_from_server (el.x86.linux.bin)
                #2  0x00000000004d1f11 start_rendering (el.x86.linux.bin)
                #3  0x00000000004d2947 main (el.x86.linux.bin)
                #4  0x00007f47d07f4040 __libc_start_main (libc.so.6)
                #5  0x0000000000410b04 _start (el.x86.linux.bin)
                
                Stack trace of thread 4563:
                #0  0x00007f47d33aa8bf pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f47d360c83e SDL_CondWait (libSDL-1.2.so.0)
                #2  0x0000000000509f0e queue_pop_blocking (el.x86.linux.bin)
                #3  0x0000000000553b2e load_enhanced_actor_thread (el.x86.linux.bin)
                #4  0x00007f47d35caaf8 n/a (libSDL-1.2.so.0)
                #5  0x00007f47d360c019 n/a (libSDL-1.2.so.0)
                #6  0x00007f47d33a5314 start_thread (libpthread.so.0)
                #7  0x00007f47d08bc3ed __clone (libc.so.6)
                
                Stack trace of thread 4564:
                #0  0x00007f47d33aa8bf pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f47d360c83e SDL_CondWait (libSDL-1.2.so.0)
                #2  0x0000000000509f0e queue_pop_blocking (el.x86.linux.bin)
                #3  0x0000000000553b2e load_enhanced_actor_thread (el.x86.linux.bin)
                #4  0x00007f47d35caaf8 n/a (libSDL-1.2.so.0)
                #5  0x00007f47d360c019 n/a (libSDL-1.2.so.0)
                #6  0x00007f47d33a5314 start_thread (libpthread.so.0)
                #7  0x00007f47d08bc3ed __clone (libc.so.6)
                
                Stack trace of thread 4566:
                #0  0x00007f47d33aa8bf pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f47d360c83e SDL_CondWait (libSDL-1.2.so.0)
                #2  0x0000000000594447 custom_update_thread (el.x86.linux.bin)
                #3  0x00007f47d35caaf8 n/a (libSDL-1.2.so.0)
                #4  0x00007f47d360c019 n/a (libSDL-1.2.so.0)
                #5  0x00007f47d33a5314 start_thread (libpthread.so.0)
                #6  0x00007f47d08bc3ed __clone (libc.so.6)
                
                Stack trace of thread 4565:
                #0  0x00007f47d33aa8bf pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f47d360c83e SDL_CondWait (libSDL-1.2.so.0)
                #2  0x0000000000594447 custom_update_thread (el.x86.linux.bin)
                #3  0x00007f47d35caaf8 n/a (libSDL-1.2.so.0)
                #4  0x00007f47d360c019 n/a (libSDL-1.2.so.0)
                #5  0x00007f47d33a5314 start_thread (libpthread.so.0)
                #6  0x00007f47d08bc3ed __clone (libc.so.6)
                
                Stack trace of thread 4571:
                #0  0x00007f47d33ada7d __nanosleep (libpthread.so.0)
                #1  0x00007f47d360e655 SDL_Delay (libSDL-1.2.so.0)
                #2  0x0000000000529575 update_streams (el.x86.linux.bin)
                #3  0x00007f47d35caaf8 n/a (libSDL-1.2.so.0)
                #4  0x00007f47d360c019 n/a (libSDL-1.2.so.0)
                #5  0x00007f47d33a5314 start_thread (libpthread.so.0)
                #6  0x00007f47d08bc3ed __clone (libc.so.6)
                
                Stack trace of thread 4572:
                #0  0x00007f47d08b5313 __select (libc.so.6)
                #1  0x00007f47d2717d8f SDLNet_CheckSockets (libSDL_net-1.2.so.0)
                #2  0x00000000004eac68 get_message_from_server (el.x86.linux.bin)
                #3  0x00007f47d35caaf8 n/a (libSDL-1.2.so.0)
                #4  0x00007f47d360c019 n/a (libSDL-1.2.so.0)
                #5  0x00007f47d33a5314 start_thread (libpthread.so.0)
                #6  0x00007f47d08bc3ed __clone (libc.so.6)
                
                Stack trace of thread 4567:
                #0  0x00007f47d33ada7d __nanosleep (libpthread.so.0)
                #1  0x00007f47d360e655 SDL_Delay (libSDL-1.2.so.0)
                #2  0x00007f47d360e6a2 n/a (libSDL-1.2.so.0)
                #3  0x00007f47d35caaf8 n/a (libSDL-1.2.so.0)
                #4  0x00007f47d360c019 n/a (libSDL-1.2.so.0)
                #5  0x00007f47d33a5314 start_thread (libpthread.so.0)
                #6  0x00007f47d08bc3ed __clone (libc.so.6)
                
                Stack trace of thread 4570:
                #0  0x00007f47d08b35bd poll (libc.so.6)
                #1  0x00007f47ba5398d6 n/a (libasound.so.2)
                #2  0x00007f47d22d21fa n/a (libopenal.so.1)
                #3  0x00007f47d22d6be7 n/a (libopenal.so.1)
                #4  0x00007f47d33a5314 start_thread (libpthread.so.0)
                #5  0x00007f47d08bc3ed __clone (libc.so.6)

**Comment by pjbroad** [comment]
I've committed a possible fix for this here: (https://github.com/raduprv/Eternal-Lands/commit/dadd5d127c1b187d7ad9a486ba0e83a025c67b17)
