### ISSUE TITLE
(Enhancement) Total Exp in Session for the 179:ers

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#154]
With 87 characters currently at OA 179 and more to come, I was thinking maybe this could get changed:

![Screenshot_20210912_201316](https://user-images.githubusercontent.com/2794779/132998325-7b505cc8-f352-4ba5-ad72-95dc19d048c9.png)

We get no way of seeing our total exp in all skills for the session.

Even though we're not collecting OA anymore, we'd still like to see how much we've gotten "overall" that session without the #calc command. ;) 

Using the OA as told by the server is probably necessary for <179 (with that one special day where OA exp ends up being more than the total of skills), but perhaps a check at the start of a session on the first experience received, if the OA remains 0 then calculate the total exp instead? Just a thought.

**Comment by pjbroad** [comment]
Sounds like a good thing to do, as you suggest.  I'll take a look at it.

**Comment by pjbroad** [comment]
Committed a change: Shows total session exp if greater than OA session exp.

**Comment by feeltheburn** [comment]
Seems to be working fine. Thanks!
