### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by mitchngwen** [raduprv/Eternal-Lands#155]
I cannot find anywhere else to ask this, is there a way for me to play this offline on local lan with just my family? Sorry if asking here upsets anyone.

**Comment by gvissers** [comment]
> I cannot find anywhere else to ask this, 

Well, there are the [official game forums](http://www.eternal-lands.com/forum/), a question the "Help me" section or "General chat" is usually answered reasonably quickly.

> is there a way for me to play this offline on local lan with just my family? 

Having a boy who loves to explore the EL maps, but doesn't really speak English well enough yet (or know how to type, for that matter), to let loose in the game, I can sympathise.

Unfortunately, the official server code is not available, not even for local use. [Here](https://github.com/UnoffLandz/unoff-landz) is an unofficial server, but I have no idea if it (still) works, what it supports, and if it doesn't send your credit card number to the developer. 

As somewhat of a workaround, if you are just looking for a quiet place to introduce your family to the game, you could try using the test server. It is meant to try out new features for the game server, but those don't happen very often, and it is empty of other players apart from the occasional developer wanting to try something out. Unfortunately, at this time there are new maps being tested on this server for a new release, so the server maps don't exactly match the maps distributed with your client, You could unexpectedly disappear under ground or not be able to access places you would expect to be able to reach.

**Comment by feeltheburn** [comment]
The short answer is no. The question seems focused on playing offline (having own server) and no, there's no servers available except the official online ones. 
The linked unoff server is long abandoned and from my recollection didn't do much other than log in.

Can't recommend using the Test server either, especially not right now.
Best suggestion is play on the official server, once characters are at the min requirements create a guild for the family. 

(This should be closable.)

**Comment by gvissers** [comment]
> (This should be closable.)

Agreed, closed.
