### ISSUE TITLE
Suggestion (minor): Meat cooked count

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#157]
Maybe something to add to the Events count (or "raw meat" in Used Items count... I dunno), but maybe somewhere keep track of how much meat is cooked.

Text 1: You cooked the meat! (indicates 1 raw meat cooked)
Text 2: You cooked 10 raw meat using the frying pan! (10 raw meat cooked)

These texts are in the same color as a PM.

**Comment by pjbroad** [comment]
It's trivial to add this but the use of Raw Meat is already counted in the Used Items count, both single and x10 cooking update the counter as you'd expect.  So a count of "Cooked Raw Meat" would be the same value as just used Raw Meat.
