### ISSUE TITLE
"You cannot access the storage from here!" multiple text to single line

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#161]
If you're too far from storage or whatever, you get: 

You cannot access the storage from here!

when you click "Sto All". The text appears once for every item in inventory, makes for heavy spam.

Suggesting: Change this so it mutes any multiple posts of this text, only showing it once on click, not once for each item.

**Comment by gvissers** [comment]
Yeah, this is annoying. I implemented you suggestion of limiting it to once per click in c7add8e3. 

This should really be handled by the server, though.

**Comment by feeltheburn** [comment]
Thx, yeah probably should be, but Sto All may be a later addition that the original storage code wasn't designed to handle.

Posted here since bluap's fixed several of these multiple-post messages in the client already.
