### ISSUE TITLE
(minor tweak) Close open bag window on #disco

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#165]
On using #disco command, any open window of a bag on the ground should probably close. 

The bag may not be there when logging back in (without closing the window).

**Comment by pjbroad** [comment]
Looks like the bag is not accessible even if you reconnect so the has to be reopened anyway.  The #disconnect command is no different to being disconnected for other reasons so perhaps it should be closed for all disconnects.  However, leaving the bag open is a good reminder.  I'm not sure....

**Comment by gvissers** [comment]
Haven't tested this, but if the effect is that we have an unresponsive open bag window, I'm in favour of closing on disconnect. If we don't do this, we should at least add some sort of visual clue that the bag is currently inaccesible.

**Comment by feeltheburn** [comment]
It's an unresponsive bag if it's gone. I #disco'ed an alt, took the bag with my main, then space-barred the alt back online. Bag was still open and there, but there was no actual bag. 

(Unless there's a way to confirm the bag is actually still there, I'd say just close it.)

**Comment by pjbroad** [comment]
Agreed.

**Comment by pjbroad** [comment]
I've committed my changes.

**Comment by feeltheburn** [comment]
Yeah, that sounds like the best option. It closes invalid bags when it's actually needed so that works. :) 

Haven't tested but will close, reopen if an issue is seen with it when I do update.
