### ISSUE TITLE
Intel HD/Windows water reflection

### ISSUE THREAD

**Issue by gvissers** [raduprv/Eternal-Lands#166]
I have been looking at problems with water reflection using Intel integrated graphics on Windows, see [forum thread](http://www.eternal-lands.com/forum/index.php?/topic/61645-water-display/). I use an Intel HD 530 chipset on Linux without problems, but using Windows in Virtualbox I can see similar issues as described in the thread. I don't know which problems are due to Virtualbox, and which are due to Windows, but so far I have found:
* To render the reflections, (part of) the 3D scene is rendered to a texture, which is blended by a shader with the water tile and a noise texture to create the reflection. On affected systems, this texture is flipped vertically, which makes the reflection look like it was reflected in the wrong plane.
* We could work around the first issue by just flipping the texture coordinate in the water shader, but apparently the winding direction is also affected, as we then see the back/inside of the reflected objects. We could work around that as well by culling GL_BACK instead of GL_FRONT, but strategically placing a reflection in the y-plane on the projection matrix instead (and flipping the sign of the y-component in the skybox view as well), lets us work around it without having to change the shader file. 
* ~However, the GLSL implementation seems to have a problem with some assignment operations. For instance, the line that adds the noise displacement:~

        reflection_tex_coord += noise_diplacment * noise_scale.xy;

    ~gives some very strange artefacts, whereas explicitly constructing a new vector~

        reflection_tex_coord = vec2(reflection_tex_coord.x + noise_diplacment.x * noise_scale.x,
                reflection_tex_coord.y + noise_diplacment.y * noise_scale.y);

    ~seems to work as it should. With this changed as well, I get a reflection in Windows that looks very similar to that in Linux. Which is a good thing because I was about to throw in the towel in frustration.~
That wasn't true, the issue is with the texture coordinates of the water tile. Investigating further.

I'll try to come up with a proper patch that detects if the texture is rendered upside down, but the last point will also require a new shader file to be distributed.

**Comment by gvissers** [comment]
Well, looks like the third point above may be valid after all. I've created a pull request (#167), as I don't feel comfortable pushing this without further testing, but with these changes the water reflection is rendered properly over here, both in Windows/VirtualBox and in Linux/native.

**Comment by pjbroad** [comment]
I've noticed I get an "OpenGL invalid enumerant" error from the glCullFace(GL_NONE) statement in check_flip_fbo_texture().  Looks like GL_NONE is not a valid for the function.  It still works but you may want to check.

**Comment by gvissers** [comment]
> I've noticed I get an "OpenGL invalid enumerant" error from the glCullFace(GL_NONE) statement in check_flip_fbo_texture(). 

And rightfully so. Now how did that end up in there? You'd just disable culling if you wanted to do that. Besides it's useless here, we only draw a single pixel, no faces involved. That's what you get for copying random code off of the internet, I suppose.

Fixed, thanks.

**Comment by gvissers** [comment]
While the original problem referenced in the original problem description was easily fixed, there were three different problems that needed their own fixes as well, culminating in the creation of an entire new water shader. All known problems seem to be fixed and are in the latest release, so closing this.
