### ISSUE TITLE
Please add an option to keep EL window on top under Linux

### ISSUE THREAD

**Issue by hussamT** [raduprv/Eternal-Lands#17]
Most window managers follow the fdo standards http://standards.freedesktop.org/wm-spec/1.3/ar01s05.html 
Look for _NET_WM_STATE_ABOVE.
It would be a nice option under the Linux client (Maybe in view options -> controls). I have no idea if other operating systems have such an option but this supposedly works on any window manager under X11.

**Comment by pjbroad** [comment]
I use the a Gnome 3 desktop.  For this, the window control menu has the "Always on top" option, it is enable and does already work for the EL window.  I'm not sure what that means....

**Comment by gvissers** [comment]
FWIW, a similar option ("Keep above others") works in KDE 4 as well.

**Comment by hussamT** [comment]
Yeah, I was thinking of an option to automatically do that as in have EL optionally tell the window manager to place the window on top.
Anyway, I worked around it by adding a rule in kwin settings to always put EL windows on top (rule based on window class) so it's fine.

**Comment by doyousketch2** [comment]
It's fine in XFCE.  You just right-click the bar on top of the window, or tab at the bottom of the screen, then select Always On Top.

**Comment by pjbroad** [comment]
Hopefully Hussam, you're happy for me to close this one.

**Comment by hussamT** [comment]
Oh yes of course.
