### ISSUE TITLE
Can not build windows binary

### ISSUE THREAD

**Issue by dunhao** [raduprv/Eternal-Lands#170]
Hello.
Thanks for developing/maintaining this project.

I have some issues with compiling on windows PC.

This is the online guide I found and tried to follow.
https://github.com/raduprv/Eternal-Lands/issues?q=windows

Here are my setup.
Specs:
- Windows 10, (Tried 11)
- Intel Core CPU with x86_x64
- Dev CPP 4.9.9.2 (Followed with building steps)

But I am having many library mismatch compile errors.

Would you please help me resolving this issue?
Do you have any up to date guide line to build?

The other question is, where can I find server side project?

Thank you.
![Screenshot_1](https://user-images.githubusercontent.com/26085551/148705122-e951802f-e8fd-4435-8be9-f7decf0a9308.png)

**Comment by gvissers** [comment]
The link that you provide leads to a list of issues containing the search term 'windows' for this repo, not to build instructions.

If you happen to refer to [these instructions](http://www.eternal-lands.com/forum/index.php?/topic/35624-windows-compilation-guide/), that guide is positively ancient, and needs to be updated. If you just want to build the client and be done with it, @pjbroad has put together [compilation guides](https://github.com/pjbroad/el-build-methods) for a number of platforms, including [Windows](https://github.com/pjbroad/el-build-methods/tree/master/windows-10/msys2).

If you want to continue using Dev-C++ (I'm actually surprised it still exists), many of the links in CK's forum post may be outdated, but the most pressing issue (and the reason for the SDL_keycode.h include error you are getting) is that the client has switched to using SDL2 (not SDL1), which you can download [here](https://www.libsdl.org/download-2.0.php). The glext.h issue I cannot help you with (it seems to want to include a Khronos specific file?), but if you use a more recent version of Dev-C++ (see e.g. https://sourceforge.net/projects/embarcadero-devcpp/), you will probably not have to replace glext.h with the version mentioned in the post.

Take all this with a grain of salt though, as I don't normally use windows, haven't touched dev-c++ in years, and when I do compile a windows client I use msys2 in a virtualized Windows environment. Perhaps someone with more experience compiling on Windows can weigh in.

**Comment by dunhao** [comment]
Hello @gvissers 
Thank you very much for your help.
That is exactly what I wanted and it works great.

**Comment by dunhao** [comment]
@gvissers ,

The other question is.
I was trying to find the server side code, but was not able to find one.

It would be much appreciated if you can let me know whereabout the server side repo...
Hope you are having good weekends!

**Comment by raduprv** [comment]
Hi
The server is not open source, only the client is.

**Comment by dunhao** [comment]
> 

Ah okay thank you for letting me know!

**Comment by gvissers** [comment]
Closing as the issue seems to be resolved
