### ISSUE TITLE
Call to check_flip_fbo_texture() breaks the new character scene

### ISSUE THREAD

**Issue by pjbroad** [raduprv/Eternal-Lands#177]
Zel reported that the new character scene is broken in the latest client.  I've traced the problem to the check_flip_fbo_texture() call in init.c, if you do not call the function the new character scene looks fine.  Also, with the call made and the scene broken, the scene can be fixed by toggling the shadow mapping option off/on.  I assume that the GL state is being left in a state that is not initialised properly when entering the new character scene.
Given you recently wrote that function @gvissers you will probably be able to fix this in a fraction of the time it would take me......

**Comment by gvissers** [comment]
Lol, "you broke it, you fix it" ?

Hopefully fixed now, I don't see a problem anymore.

**Comment by pjbroad** [comment]
> Lol, "you broke it, you fix it" ?

Ops, didn't mean to sound like that.

> Hopefully fixed now, I don't see a problem anymore.

Yep, fixed. thanks for looking at it.

**Comment by pjbroad** [comment]
Fixed in d16a011d7d6399f9a8f9b86d007a64996c97ebee
