### ISSUE TITLE
init.c:819: Fatal error while loading data files. Either set the data_dir correctly or run from the data directory.

### ISSUE THREAD

**Issue by VdeVatman** [raduprv/Eternal-Lands#18]
I'm having this error after trying to execute EL's compiled binary:

```init.c:819: Fatal error while loading data files. Either set the data_dir correctly or run from the data directory.```

 Which would be the data directory?

**Comment by pjbroad** [comment]
Have you downloaded and unpacked the data files? The data directory is whereever you unpacked the files, in the top level of that location. You can unpack the files anywhere then run the client binary from that location.  Once you have an initial configuration file (in $HOME/.elc/main created after running the client once) you can edit the el.ini file and change the data_dir value to the correct location.  You can get the data files from here http://twinmoons.org.uk/el/rel/194/EL-1.9.4-all-datafiles.zip. This is the same data pack used to create the client+data packages on the EL download page http://www.eternal-lands.com/page/download.php.

**Comment by VdeVatman** [comment]
I downloaded the source without the installer script, now it is fixed.
