### ISSUE TITLE
Can we remove UVP: 1 now?

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#183]
This seems more like a debug text than a necessity. It can easily be determined by checking the settings, and is not something the player needs to constantly see.

Maybe it was necessary "back in the day", but perhaps we can get rid of the "UVP: 1" line when showing FPS now?

![Screenshot_20220321_131106](https://user-images.githubusercontent.com/2794779/159258410-f5c94a5a-de42-44c1-a9be-f4a852af7ced.png)

**Comment by pjbroad** [comment]
If you exit with it enabled, your character should be visible when you restart.  I have it disabled because it makes your eyes look weird.  I briefly looked into why that was but could not find a solution.  Disabling it does not appear to impact performance as far as I can tell.

**Comment by gvissers** [comment]
> If you exit with it enabled, your character should be visible when you restart. 

Hmm... That works somewhat, but the texturing is gone:
![uvp](https://user-images.githubusercontent.com/1096355/159264634-f65b6762-76cd-4136-88e0-5fe7e28db867.png)

> Normally there is not much of a difference with UVP on, but in invasions there's quite a difference.

Okay, that makes sense. I'll see if I can translate the shader to GLSL at some point.

**Comment by raduprv** [comment]
That would be great!

**Comment by feeltheburn** [comment]
I've had UVP on (1) since as far back as I can remember, turning it off and on has no effect here. 

But thanks, my reason for posting this is done. Y'all seem to be discussing other related stuff so I'll leave it open. You can close it if/when the other talk's done. :)

**Comment by feeltheburn** [comment]
I'll close this to clean up clutter. (If this extended stuff needs discussion a new issue may be better suited for it.)
