### ISSUE TITLE
Green watery gunk becomes regular water when reflections on

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#193]
![isbroken](https://user-images.githubusercontent.com/2794779/167820791-ff70f0d7-8bd8-46dd-9971-66d76687fcdf.jpg)

As can be seen, this rarely used green watery-type ground tile turns into regular water when reflections are turned on.

**Comment by feeltheburn** [comment]
https://github.com/raduprv/Eternal-Lands/pull/194

Submitted a pull request that fixes it.

As seen below, the green gunk remains the same with reflections on, just like lava and dirty waters. All water types are displayed, showing the fix does not affect any of them.

![isfixed](https://user-images.githubusercontent.com/2794779/167821895-2116fd3e-05dd-4479-84c4-6b2639a3b46c.jpg)

**Comment by castixllc** [comment]
If I'm seeing the first picture correctly, it doesn't turn into a regular water tile, but a slightly greenish water (compare it with regular water in the lower right). I will admit that I had expected the effect of the water texture to be stronger, though, also for the tile under the lava. Fix looks fine to me, if you are happy with water tiles 233-239 not reflecting.

**Comment by gvissers** [comment]
If I'm seeing the first picture correctly, it doesn't turn into a regular water tile, but a slightly greenish water (compare it with regular water in the lower right). I will admit that I had expected the effect of the water texture to be stronger, though, also for the tile under the lava. Fix looks fine to me, if you are happy with water tiles 233-239 not reflecting.

**Comment by feeltheburn** [comment]
233-239 do not exist, and pretty much zero chance they ever will with there being no use for them as the maps are at a pretty much set state.

If a new reflective water gets added, testing it will show this file needs to change with it, and it would be better to number it in the 221-229 fields, changing #define IS_WATER_TILE(i) (!i || (i>230 && i<255)) to i>220.

**Comment by feeltheburn** [comment]
This is the lower end of the tiles as shown in the map editor. "0" at the very top is the most commonly seen water, then there's the 6 "water" tiles seen here. All 7 total are seen in the above images.

As the white areas show, there's a wealth of unused numbers. 

![tiles](https://user-images.githubusercontent.com/2794779/167827076-ab65f4e8-8690-4c60-be76-464dcf18a00c.png)

**Comment by feeltheburn** [comment]
Closing as the commit solves the issue.
