### ISSUE TITLE
Big Enhancement for 1.9.7: Ending the You Are Too Far Away nightmare

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#199]
It has always been one of the biggest annoyances in the game, being not that far from a creature but still being told "you are too far away" when clicking on it then you completely stop moving as if you don't still want to head towards it.

This has gotten much worse with the improvements to clicking  on an "area" to click on the creature that came with android work. (I absolutely love this, btw, so not complaining about it.)

But it's lead to even more "you are too far away" messages because you get that even clicking near a creature with that feature. It can sometimes be very difficult to try and click to get near the creature enough to click on it at all.

The recommendation is to change this so that instead of "you are too far away", you just keep heading towards where the creature is. **If  a creature is outside of the clickable range, the coordinates of the click are grabbed and treated like a normal walk instead.**

Not following the creature around if it moves, just going to the location that the player made the click.

@pjbroad I think it was you that said this was possible on the EL forum once, but I can't find where it was said and I'm not 100% certain it was you.

I think this could be one of the big changes that would make 1.9.7 a worthwhile upgrade. And fix an annoyance that is the exact opposite of what is expected when trying to move in any game. The click area on creatures shouldn't be a reason to completely stop movement.

**Comment by pjbroad** [comment]
I've committed a change to do this.  On by default, there's an option on the CONTROLS tab to enable/disable.  When you click and are too far, you move to the click location instead.  The message is surpressed.  The location is highlighted too.

**Comment by feeltheburn** [comment]
It takes some getting used to, but once you do it's much much better than making complete stops when clicking critters.

Thanks! Gonna close unless something new is discovered. I'll continue using it on testing servers.
