### ISSUE TITLE
Background on S H P M indicators won't stay on

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#20]
For the right-click "Background On" option for the  S H P M indicators, the background will turn off by itself when you press TAB to go from viewing the tab map back to regular game view. There's basically no way to keep the background on with this happening, which I prefer as it makes the letters more noticeable.

Possibly other ways, but that's a confirmed one.

**Comment by pjbroad** [comment]
Thanks, fix committed.
