### ISSUE TITLE
Force "stand up" if sitting on shapeshift

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#22]
If the player shapeshifts (to mule/phoenix), would it be possible to check if the player is sitting, and if so force the player to standup when the shift occurs?

As there is no "sit" while shapeshifted, this shouldn't be a problem to automatically do for the player.

This is an old "annoyance" because stand doesn't work after the shift, and while there's ways to work around it, a sitting player can't just click to move when shifts (when the setting to not move while sitting is on, which it is for most).

**Comment by raduprv** [comment]
You mean there is an issue with the sit lock? I think the client should 
ignore the sitlock settings while polymorphed. Doing it on the server 
would require an extra delay for the stand up animation.

**Comment by feeltheburn** [comment]
Right, if "sit lock" is set, and you're sitting when you click a glyph, you're considered "still sitting" after you shapeshift and cannot click to move.

Pressing the "stand up" button after shifted does not help, which is the obvious first thought.

Opening Options and turning off Sit Lock will allow you to walk, but if turned back on before you un-shapeshift, you're once again unable to walk. Even after you've walked while shifted, it still considers you to be sitting in this scenario. 

(Replication:
1- Make sure "Sit Lock" option is on.
2- While sitting, click a glyph.
3- Try to walk after shifted by clicking the ground around you.
4- Turn off Sit Lock, you can now walk.
5- Turn if back on again after having walked, it'll still treat you as if you're still sitting.)

I submitted it here in hopes there's a way to do it on the client side.


There is a possible server fix, in that it could check if sitting when a glyph is clicked, and if so it gives an error message to stand up first. This done the same way it checks if you're in running mode, and tells the player "not while running" and won't shapeshift. (As a 24/7 runner, I see that one almost every time, hehe.) But I was thinking there may be a way to do it client-side, I'm not sure.

**Comment by pjbroad** [comment]
It's been a while since I last looked at the client code regarding shape-shifting but do remember having trouble identifying when a character was in that state. It might be easier if the server forced a standing position when you transform, then prevented you sitting again until you return to normal.

**Comment by feeltheburn** [comment]
The latter part's not necessary, nothing happens when you try to sit while shapeshifted (confirmed with tests).

The only issue is the need to be standing when the glyph is initially clicked.

**Comment by raduprv** [comment]
Ok, I made that change in the server, you won't be able to shapeshift 
when standing.

**Comment by feeltheburn** [comment]
Nice. Thanks!
