### ISSUE TITLE
ranging lock indicator

### ISSUE THREAD

**Issue by hussamT** [raduprv/Eternal-Lands#23]
Hi. Is it possible to add 'ranging lock' on/off indicator in the lower right side of the window near the Special|harvest|poisoned|messages indicator?
Thank you.

**Comment by pjbroad** [comment]
It would be very easy.  How about "R" for the indicator text, with "Ranging Lock On" and "Ranging Lock Off" for the hover text and "Ranging Lock Status" for the context menu.  We could also  enable/disable the lock by clicking the indicator.

**Comment by hussamT** [comment]
On Sat, 2016-04-23 at 03:00 -0700, Paul Broadhead (bluap in EL) wrote:
> It would be very easy. How about "R" for the indicator text, with
> "Ranging Lock On" and "Ranging Lock Off" for the hover text and
> "Ranging Lock Status" for the context menu. We could also
> enable/disable the lock by clicking the indicator.
That would be great. Thank you.

**Comment by pjbroad** [comment]
OK, I've committed the change.
