### ISSUE TITLE
Alt+x and Ctrl+q are hard wired, to quit

### ISSUE THREAD

**Issue by jiyunomegami** [raduprv/Eternal-Lands#26]
Ctrl-i to open the inventory is rather awkward with one hand, so I put this in my key.ini
```
#K_ITEMS = LCTRL q
```

I think check_quit_or_fullscreen should check they key bindings first before quitting.

**Comment by pjbroad** [comment]
Hi.  That should work but you need to redefine #K_QUIT_ALT to something else too.

**Comment by jiyunomegami** [comment]
I see. Thanks!
The comment in check_quit_or_fullscreen and the all caps variables starting with K_ (read as "Constant") confused me...
```
	// first, try to see if we pressed Alt+x or Ctrl+q, to quit.
	if (key == K_QUIT || key == K_QUIT_ALT)
```
And there is no #K_QUIT_ALT in the default key.ini, probably because the default is different on linux/win/mac.
