### ISSUE TITLE
Particles not showing in zoomed out camera view

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#31]
Particles do not get rendered if the camera is more than 4.5 or so "zoomed out".

The 4.5 being a reference to the Camera > Maximum Camera Zoom Out option which goes up to 8.0.

https://youtu.be/JNm3vhjFYx0 

Not the greatest video, but you can see this in action. I start with the camera at a full "8.0" zoomed out as far as possible and slowly zoom in. At around 11 seconds, you see the particles for the Bethel fast-heal waterfall suddenly make an appearance. They disappear at around the same zoom later when zooming back out.

Noticed this a long time ago, but simply didn't care. However as I go through all the maps while editing I'm noting particles can be a necessity in certain situations to make some sense of the design.

This may possibly be a result of the client having had the "Maximum Camera Zoom Out" changed a couple releases back to allow it to go further out. Particles may possibly have been limited to the original max camera and need to be changed to show up to the current zoom out?

This happens with all particles that I've noticed, not just the shown example.

**Comment by pjbroad** [comment]
You were correct that the extended zoom is the cause.  To keep the particle size consistent, I've simply capped the impact of the zoom out.
