### ISSUE TITLE
SDL2 port

### ISSUE THREAD

**Issue by raduprv** [raduprv/Eternal-Lands#32]
Is there anyone willing to work at a SDL2 port?
This would enable us to eventually have GLES support, Android, etc. We can also implement touch and other things specific to phones and tablets.

**Comment by pjbroad** [comment]
I'm picking this up from the previous work: Sir_Odie's unfinished branch on the desktop client and Radu's work on the Android client.

**Comment by pjbroad** [comment]
Initial working version committed dcdc6fd73792c02cabf8f897148012f8ecedfcaa

**Comment by pjbroad** [comment]
Addressed with release [1.9.5p6](https://github.com/raduprv/Eternal-Lands/releases/tag/1.9.5.6).
