### ISSUE TITLE
Android port discussion

### ISSUE THREAD

**Issue by raduprv** [raduprv/Eternal-Lands#37]
I did some good progress on the Android port. Not yet playable, but good progress nevertheless.
I would like to have a dev meeting in game, or skype or ICQ to discuss about a few things, such as how to handle the touch based events, and a few other things.
Let me know if you can do that, and when it would be a good time for you.

**Comment by raduprv** [comment]
Well then, since no one is interested in working at it, are there any objections if I just make the Android version a new project in itself? There are quite a few non Android things that I have to #ifdef out, and add Android stuff, so it is getting messy.

**Comment by pjbroad** [comment]
As this is done, I guess we should close it.  Perhaps open a new issue to work on merging the changed code back into this repo.
