### ISSUE TITLE
Map editor - Option to turn reflections off ("code" included, just need implement)

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#40]
My Perl-only brain ain't helping with this, but it should be quite simple to do. I can explain what to do, just not sure how to properly implement it.

In map_editor/mapedit.ini -

add these 3 lines 

```
Reflections when editing maps with water can be problematic, not recommended while editing.
Turn on only if you actually need them for some reason.
#show_reflections = 0
```

Then in map_editor/draw_scene.c , change line 87 to something like this:
```

    if(show_reflections)
        any_reflection=find_reflection();  // <- the actual line 87
    else
        any_reflection=0;
```

(Actually, any_reflection is set by default to 0 at the top of the void this is in, so the "else" part is unnecessary. Leaving to indicate the proper result for any_reflection.)

Not sure if that's the proper way to do it in C++, but the basic gist is if show_reflections in mapedit.ini is 0, then don't bother with find_reflection and set any_reflection to 0 so future calls to reflections will be skipped.

My main issue is I'm not sure how to call the value of show_reflections in C++, otherwise I'd have tried doing this myself.

(I have tested this by just directly setting any_reflection to 0 and compiling that way... huge improvement in the editor working around water.)

The option to turn off reflections not only turns off reflections, but the entire screen's background color doesn't change to blue just because water shows up... one of the single most annoying aspects of the editor. I really wish I'd thought to change this sooner.

**Comment by feeltheburn** [comment]
What this option does: 

In the current editor, you get reflections and the full screen turns blue anytime a random water piece is on the screen. I've turned off ground tiles in these images so you can better see the blue and reflections.

![editor-reflect](https://cloud.githubusercontent.com/assets/2794779/23697909/d73de228-03e9-11e7-8e26-fafda21e3669.png)


With reflections turned off, that same scene has no reflections (obviously), and ONLY the water tiles are blue.

This is a HUGE improvement on the eyes when trying to edit maps.

![editor-noreflect](https://cloud.githubusercontent.com/assets/2794779/23697986/2c597de4-03ea-11e7-9a09-67c581431800.png)

**Comment by pjbroad** [comment]
Finally implemented :)
