### ISSUE TITLE
Storage item count under the scroll bar

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#43]
![storage](https://user-images.githubusercontent.com/2794779/28474503-46ae1280-6e49-11e7-90f9-0b920302a29c.png)

Not the best example, but enough to show it... is it possible for the number text to be above the scroll bar on the right? Without it causing other issues, that is.

There are times it's hard to distinguish the actual count, just not in this particular shot.

**Comment by pjbroad** [comment]
There are two counts.  One fixed when you click the item, the other follows the mouse.  I presume the mouse hover one is OK; you just move the mouse.  For the fixed (clicked item), how about aligning it with the right edge of the items slot if the text reaches beyond the grid boundary?

**Comment by feeltheburn** [comment]
Technically hover is okay (move mouse) but it shows under it as well.

Any option where the number doesn't get hidden is fine, so yeah, right-edge alignment should be fine.

**Comment by pjbroad** [comment]
Fixed using new ELW_HANDLER_POST_DISPLAY callback.
