### ISSUE TITLE
Cosmetic - Lines around "bag" squares

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#46]
![spectacle t29156](https://user-images.githubusercontent.com/2794779/34673585-059deb24-f483-11e7-8102-dc78891d963f.png)

The left and bottom of the bag look a bit awkward without lines to show the full squares, it just "feels" like something's missing when you look at it.

Obviously just a cosmetic issue, but if it's possible perhaps it would look better with lines?

**Comment by pjbroad** [comment]
Have you set the "Adjust Graphic X/Y" values on the troubleshooting tab of the options window to good values?  The easiest way to check is to look at the tabs on windows, they should be straight and sharp.  I can reproduce what you see by setting my values of  "Adjust Graphic X/Y" to be off.

**Comment by feeltheburn** [comment]
![screenshot_20180112_094012](https://user-images.githubusercontent.com/2794779/34866349-9cc58538-f77c-11e7-8ea5-e5a835183a03.png)

Aha. Was unaware of those settings. x -1, y 1 seems to do the trick.
