### ISSUE TITLE
Deleted object being used to determine what to show on insides maps

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#48]
TBH this can wait till 1.9.6 if it can't be figured out quickly.

There's coding for inside (dungeon) maps that if something is too far separated by blank space, it cannot be seen. For example, a map with house insides, if separated by enough space you cannot see the insides of other houses in the distance when you enter one. 

This is broken by deleted objects. When a 3D object is deleted in the map editor, the 'blending_level' gets set to 20 rather than completely removing it from the file, to prevent changing of object ID numbers. 

The code to "not see" the insides of other areas does not take this into account, and uses the deleted objects in determining what to show.

**Example**: a map has 2 house insides, and you cannot see one from inside the other.

I place an object between them that makes them too close, and you can now see one from inside the other.

I delete the object with no other changes. The client is still reading that deleted object is there, and you can still see inside one from the other.

**What should happen**: The code that determines what inside area to show should strip any objects with a blending level of 20 from information first before making this determination.

**Also**: Perhaps in the map editor code, when an object is deleted, it doesn't just set blending_level to 20, but also the position x and y both to something like -60, way off the map?

**Comment by feeltheburn** [comment]
While this might fix a place or two, it's just cosmetic and can wait till a future release. It's mostly just affecting me when I work on maps, and I'll be taking a break from that when this release happens. ;-)

**Comment by pjbroad** [comment]
It may be a simple fix, do you have an example location when this happens?

Also, as for changing the location of deleted objects too, could this be applied to existing maps by writing a simple, off-line file processor?

**Comment by feeltheburn** [comment]
Ugh, I wouldn't trust myself to hack the elm files. I use someone else's script just to get info. 

If it can be implemented in the map editor itself, that would be great. There's only a couple possible maps I can think of that might be helped by it anyway. And those are just "might" at that. 

Also If it automatically sets the x/y off the map for blend 20 objects when it's loaded into the editor, then it should save that way as well for all old objects. If that's possible.

**Comment by pjbroad** [comment]
OK.  Rather than change the existing files, they could be corrected on load into the client.

Do you have an example location that I could test?

**Comment by feeltheburn** [comment]
One that may look different, I'm not sure. Most of what I see is when I'm creating stuff.

I can possibly set one up to test with. Bed soon, I'll post in the morning.

**Comment by feeltheburn** [comment]
Here's a sample of Naralik insides. #tp 42 45 27 to test.

![show-stall](https://user-images.githubusercontent.com/2794779/35092844-ea5e703e-fc40-11e7-9587-9c94ca32c5f0.png)

I placed a horse stall near a house inside, and it can now be seen from the magic arena.

NOTE the house insides could NOT be seen before I did this.

![show-stall-removed](https://user-images.githubusercontent.com/2794779/35092893-0eeef68a-fc41-11e7-89ed-0ae9616f75ee.png)

I only removed the stall and saved the file, so the stall is still there with blend level 20. As you can see, the insides of the house are still visible.

[map8_insides.elm.gz](https://github.com/raduprv/Eternal-Lands/files/1642431/map8_insides.elm.gz)

There's the file. Should be compatible with current and test servers, though there may be minor differences.

**Comment by feeltheburn** [comment]
I don't think the server is paying attention so well to if an object is deleted or not, at least not in every situation.

The pear was on the Trassian map today for example. Very few harvestable items and with my knowledge impossible to miss. But after going through every harvestable twice, it could not be found.

My belief is the pear was placed on a harvestable that was blend 20, deleted.


With this in mind, I think the best option is when the elm gets saved by the map editor, it checks each 3D object to see if its blend level is 20. If it is, it:

- changes the x,y to be well off the map, like **-20,-20** or so.
- changes the object itself to be **badobject.e3d**, which is an actual object though noone will see it.

Doing this on file save rather than when the object is deleted will fix any that are already deleted.


I can go through each file and "re-save" to get all the files fixed in this way. But this would solve the above issue as well as any possible others that the server might not take into account now or in the future.

**Comment by feeltheburn** [comment]
I can only barely read C/C++, so writing it could result in the annihilation of the planet. ;) 

But if I'm reading correctly, the change would need to be done in 

mapeditor/map_io.c
line 232 cur_3d_obj_io.blended  = objects_list[i]->blended;

Something like "if objects_list[i]->blended = 20", then:
- cur_3d_obj_io.x_pos = -15  (tile/2)
- cur_3d_obj_io.y_pos = -15
- cur_3d_obj_io.z_pos = 0  (not obligatory but seems like a good idea)
- cur_3d_obj_io.file_name = ????

Not sure how the file_name is done in this variable, but it should point to 3dobjects/badobject.e3d.

**Comment by pjbroad** [comment]
Could we just not write the object to the file?

**Comment by feeltheburn** [comment]
When an object is deleted, it's not removed from the file, just set to a blended = 20.

That's done to keep the object IDs the same on other objects.

When new objects are added, the code first goes through any blended = 20 items and replaces those, only adding actual new object entries when no blended 20 objects are left.


I don't know how the code itself is written for this, just how it's working. But you'd have to ensure both that the ID numbers of other objects don't change when the object is deleted, and that the lower (deleted object) ID numbers get used... which I'd imagine the code stuffs in a list when it reads in the file and looks for blended = 20. (At least that's how I'd do it.) 

The latter reuse of deleted object IDs is necessary as well as there seems to be a hard stop in IDs at around 15,000 where no more objects can be added.

I fear possibly breaking something if you just delete it, basically.

**Comment by pjbroad** [comment]
OK.  Changing the code as you suggest works if you assign the new values to objects_list[i] instead of cur_3d_obj_io.  This is because what matters is the clustering algorithm.  It also means you can achieve the same by just not calling the update_occupied_with_3d() function for a bended==20 object.  So it looks like the only change we need is:
```
diff --git a/map_editor/map_io.c b/map_editor/map_io.c
index 99cb151c..530d2d5a 100644
--- a/map_editor/map_io.c
+++ b/map_editor/map_io.c
@@ -242,7 +242,8 @@ int save_map (const char* file_name)
 #endif //ZLIBW
 
 #ifdef CLUSTER_INSIDES
-                               update_occupied_with_3d (occupied, i);
+                               if (cur_3d_obj_io.blended != 20)
+                                       update_occupied_with_3d (occupied, i);
 #endif
 
                                j++;
```
I'll commit this change if that works for you.

**Comment by pjbroad** [comment]
I've committed the change as I think it fixes the issue.  Perhaps this can be closed now.

**Comment by pjbroad** [comment]
Release in 1.9.5p4, still need the maps updating.
