### ISSUE TITLE
Compilation issue with macOS 

### ISSUE THREAD

**Issue by auvi** [raduprv/Eternal-Lands#52]
I am trying to compile Eternal-Lands on my iMac (2011) and looks like the code was not updated for Intel macs. Has there been any efforts to port the codebase to macs?
```make
$ make --file Makefile.osx
Makefile.osx:96: target `gamewin.o' given more than once in the same rule.
Makefile.osx:96: target `gl_init.o' given more than once in the same rule.
gcc -mpowerpc -malign-natural   -O -pipe -DOSX -DELC -DNO_MUSIC -DATI_9200_FIX -DBUG_FIX_3D_OBJECTS_MIN_MAX -DUSE_FRAMEBUFFER -DNEW_FRUSTUM -DAUTO_UPDATE -DNEW_TEX -DCOUNTERS -DNEW_E3D_FORMAT -DALUT_WAV -I/usr/include -I/usr/include/libxml2 -I/opt/local/include/ -I/Library/Frameworks/SDL.framework/Headers -D_REENTRANT -I/Library/Frameworks/SDL_net.framework/Versions/A/Headers/ -I/System/Library/Frameworks/OpenGL.framework/Headers/ -c -o 2d_objects.o 2d_objects.c
clang: error: unknown argument: '-mpowerpc'
clang: error: unknown argument: '-malign-natural'
make: *** [2d_objects.o] Error 1
```

**Comment by pjbroad** [comment]
There's a macosx directory in the source with a xcode project file.  It will need updating for recent file changes but should build fine once that's done.  I think the Makefile.osx needs updating too but you could try adding PLATFORM="" to the end of the command line.  I do not have access to a mac so can't test this.

**Comment by pjbroad** [comment]
What do you want to do with this issue @auvi?  We have a working xcode project file now but the Makefile.osx file is still out of date.  Did you get it working and so have an updated version we could commit?

**Comment by bendoughty** [comment]
It is probably safe to close this issue now, we have a working and up-to-date Xcode project which allows for the client to be built for both Intel and ARM-based macs.

Here's a link to the [macOS build guide](https://github.com/pjbroad/el-build-methods/tree/master/macOS/Xcode) for anybody who might stumble across this in the future.

**Comment by pjbroad** [comment]
Thanks for updating the mac build @bendoughty closing this issue.
