### ISSUE TITLE
Problems with HD laptop

### ISSUE THREAD

**Issue by fedeb95** [raduprv/Eternal-Lands#53]
Hi, I recently bought a laptop with an HD display and nvidia gpu. In the settings I've selected 1920x1080 mode, tried both 16 and 32, but if I go fullscreen the game goes off screen and I'm not able to see part of the gui, making it impossible to play in fullscreen. Please tell me how to configure the settings properly, because it's the first time I have this issue, and I'm not sure it is a bug. Thanks in advance

**Comment by fedeb95** [comment]
I managed to solve this issue by selecting dpi scaling in the compatibility settings. Sorry for not mentioning the os, I used the windows binary. Also on linux it works perfectly with the same laptop. I don't know if it's a widnows problem or of the game.

**Comment by pjbroad** [comment]
Closing as no further issues reported,
