### ISSUE TITLE
"Mixed item filter" prevents printing of item info to chat window

### ISSUE THREAD

**Issue by rauchc** [raduprv/Eternal-Lands#54]
Steps to reproduce:
- Verify that "Mixed item filter" in Chat options is activated
- Close Inventory/Manufacture window
- Click any item in a quickslot with the eye cursor

Result: Nothing gets printed to the chat console
Expected result: Item description printed to console

Version used: 1.9.5p2

**Comment by pjbroad** [comment]
OK, I see what you mean.  Unfortunately, the client currently treats all messages intended for the inventory window the same.  We should either change the name/description of the filter or add some additional logic to perhaps only block "You successfully created..." messages.  What do you think?

**Comment by rauchc** [comment]
I agree with Sir-Odie, that's how I would understand the option.

**Comment by pjbroad** [comment]
Fixed as agreed.
