### ISSUE TITLE
Server marks (newbie tutorial) remaining when switching between clients

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#56]
If a player starts the tutorial and gets a server mark on one client, and continues it on another, the server mark will remain on the first client. Only way to delete it currently is get rid of the servermarks file itself.

These would be better actually being saved and sent from the server but that probably won't happen. ;) 

But esp. now with Android out there, there should be some way to eliminate the server mark without touching files.

The only bandage I could think of to put on this wound... the player stands where the mark is at and has a #command to delete the mark at that location?

An old issue, but has been seen a couple times in chat lately.

**Comment by pjbroad** [comment]
As you can delete normal marks from the tab map, how about the same for server marks?  Alternatively, as there are not that many server marks, a #command could list then and allow you to delete them by number or name.

**Comment by reddhannta** [comment]
That may work

**Comment by feeltheburn** [comment]
Whatever is simplest, as long as it works, should be good ;)

**Comment by pjbroad** [comment]
I've added deleting server marks to the tabmap ctrl-right click feature and to the #unmark command.  While I was making these changes, I also changed the tabmap delete code to ignore marks not shown due to the marks filter.  If this is OK can we close this issue?

**Comment by feeltheburn** [comment]
I don't have server marks to test it with, but assuming it works as you state, that sounds great!

**Comment by pjbroad** [comment]
An example contents for servermarks_<player name>.dat 
```
0 64 138 ./maps/startmap.elm Lasud marker
1 697 157 ./maps/map2.elm WS Docks
```
