### ISSUE TITLE
Wakko asked: Can we change the mouse cursor colour?

### ISSUE THREAD

**Issue by pjbroad** [raduprv/Eternal-Lands#75]
EL currently uses SDL functions for the cursor and so its just black/white pixels.
https://wiki.libsdl.org/SDL_CreateCursor

Wakko asked about using textures.   The is a disabled feature in the code base enabled with #NEW_CURSOR that implements this change.  It does not currently work because there is no texture and the code was not updated properly when we moved to the new texture code years ago.

Lets fix up the code and see if we should enable it....

**Comment by gvissers** [comment]
I haven't really looked into this, but the documentation also mentions [SDL_CreateColorCursor](https://wiki.libsdl.org/SDL_CreateColorCursor). Might that be useful?

**Comment by pjbroad** [comment]
This was done a while ago and now available to all via 1.9.6.
