### ISSUE TITLE
Cut back on number of rows for items in storage

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#87]
(QoL enhancement)

We're at a point where new items pretty much don't happen, so I'd suggest two things:

1) Remove the "Quest" section in storage (it only appears when you type #sto at the very bottom after hazardous, not with normal storage use).

2) Limit the rows available for items based on how many items there are for that section. Maybe at most have 1 extra row per section more than total available items "just in case", but not 30-something rows for something like coins.

Only 6 rows of 6 items show without scrolling, and the bolded ones below are 6 rows are less.

The reason I thought about this: When speed-clicking to grab items from storage, I find I regularly misclick on the storage scrollbar, scrolling all the objects out of visibility just to see a bunch of empty rows.

The below list shows how many items could possibly appear in each section based on the server's items list I got from radu.

animal = 57 (10 rows)
armor = 102 (17 rows)
_books = 399 (67 rows)_
clothes = 152 (26 rows)
**coins = 2 (1 rows)
essences = 17 (3 rows)
flowers = 35 (6 rows)
food = 9 (2 rows)
hazardous = 6 (1 rows)
jewelry = 8 (2 rows)**
magic = 136 (23 rows)
**metals = 12 (2 rows)
minerals = 12 (2 rows)**
misc = 69 (12 rows)
**ores = 13 (3 rows)**
potions = 45 (8 rows)
**tools = 21 (4 rows)**
weapons = 116 (20 rows)

Another thought is to simply base how many rows are shown (minimum 6) based on how many objects the user has. (It would have to auto-expand as needed with new row(s) during trades and putting items in sto from inventory.)

**Comment by pjbroad** [comment]
How about we just find the last row containing an item and make the scrollbar only scrollable as needed?  I.e. disabling it in the case of nothing beyond the 6th row and scrolling just to the needed row beyond that.  This would then function the same an other scrollable windows.  I'm not sure about removing the "quest" category, I'm sure it's used for a quest at some stage.

**Comment by feeltheburn** [comment]
Well, the quest thing was just an afterthought anyway, not like it's in the way, just never actually seen it used. 


As for how to do the scrollbar, whatever works and is easiest for you is fine, the only result I'm hoping for is if the scrollbar is there and you click it, you don't end up viewing a bunch of empty rows.

**Comment by feeltheburn** [comment]
Tested. Did some bag drops and trades that affected if it would scroll.

Looks good!
