### ISSUE TITLE
Overhead count cut off if item name too long

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#89]
Overhead count doesn't show if the item name is too long, as seen here.

As the number is more important than the name, some way of truncating the name may be preferred.

![cotcount](https://user-images.githubusercontent.com/2794779/100243766-8588b300-2f36-11eb-9a98-bce8521cd03d.jpg)

**Comment by pjbroad** [comment]
Should be fixed now.

**Comment by feeltheburn** [comment]
Looks good!

![elscreen287](https://user-images.githubusercontent.com/2794779/100979264-d6566800-3543-11eb-862f-cd03912863ee.png)
