### ISSUE TITLE
Remove the "Huge" option for new maps in map editor

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#91]
The point being to ensure no one creates a new map using it. "Huge" maps do not exist in EL nor will they ever exist (only possible new maps at this point are guild maps and they're limited to Medium).

Learner has confirmed they're not needed for OL either.

Someone is creating a new guild map, surprisingly, and they had initially started on a huge map. fortunately they asked about it when they decided to start over and I have them doing a Medium.

(The 15,000 3d object limit for a single map also makes huge not really doable. PV Magic School, a Large map, has over 14,000 objects on relatively much less space than a huge map. Ida and WS are also "Large" for comparison.)

map_editor/interface.c line 942

Just remove this bit (I've already compiled this way and it's fine):

`	if (map_size == 4)
		glColor3f (0.0f, 0.5f, 1.0f);
	else 
		glColor3f (1.0f, 1.0f, 1.0f);
	draw_string (2, 6*17+2, (const unsigned char*) "Huge       [256x256]", 1);`

**Comment by brunoramoslu** [comment]
@feeltheburn Is there a technical limitation on "Huge" maps, on the server or the client?
Or it is an administrative constraint taken in consideration the points you mentioned?

**Comment by feeltheburn** [comment]
I'm sure the option was added back when the game was first created. But in the end no one ever used it because maps like White Stone and Idaloran (which are "Large") were already long treads for players. Huge being 4x larger would just be unusable.

But there is the technical limitation as well of 15,000 max 3D objects on a map. Ida and WS are over 10,000, and PV Magic School is over 14,000. All your Large maps have over 2/3 of the allowed 3D objects. A "huge" map would have to be pretty barren to work.

(As far as EL is concerned, guild maps are limited to Medium size, and those are the only maps that would be added to the game at this point. Should hell freeze over and a new official game map be needed, well, I'm the only active official map editor and I'd never even try a Huge. OL is using EL maps plus thus far their new maps have only been Medium. Learner said they may do some Large in the future, but had no use for Huge either.)

**Comment by gvissers** [comment]
Option removed.
