### ISSUE TITLE
Map Editor - can't type in Name field in Open/Save popups

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#96]
Map Editor - In the Open and Save popups, I can't seem to type in the Name field. Nothing happens on keypress.
I've confirmed that it's limited to just this program. 

I can't even confirm how long it's been this way as I normally edit already-existing maps, not create new ones.

Is anyone else having this issue? 

I'm on Linux (OpenSUSE Leap 15.2), KDE. I set this program to "ignore global shortcuts" (so the Alt key could be used) but that doesn't seem to be the issue as I turned that off to check. Otherwise I have no special settings for the editor.

![canttypeeleditor](https://user-images.githubusercontent.com/2794779/103168183-5d3fed00-4831-11eb-81ae-cbfca2374f2c.jpg)

**Comment by gvissers** [comment]
Should be fixed now, I think.

**Comment by feeltheburn** [comment]
Works, thx!
