### ISSUE TITLE
Map Editor - Not saving in gz format?

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#97]
Image used for other bug, but shows this as well.

On saving a new map file, the default name shows .elm, not .elm.gz as is the standard now.

As the editor can open/save .elm.gz files that already exist, it shouldn't be difficult to fix this so it saves as .elm.gz, right?

![canttypeeleditor](https://user-images.githubusercontent.com/2794779/103168520-2ddeaf80-4834-11eb-8e92-13dcc97d6952.jpg)

**Comment by gvissers** [comment]
It was saving in gzip'ed format, just using the wrong extension. Should be fixed now.

**Comment by feeltheburn** [comment]
Looks good, thx!
