### ISSUE TITLE
Map Editor - +/- control of grid gets lost on opening ground tile popup

### ISSUE THREAD

**Issue by feeltheburn** [raduprv/Eternal-Lands#98]
Since I'm here...

How to recreate the issue:
1) Open a map.
2) Press G to show the grid. + / - on the number pad moves it up and down.
3) Click the ground tile button at the top. Click for a new ground tile so the popup with all the ground tiles shows. + / - on the number pad scrolls through the ground tiles.
4) Close the ground tile popup. 

The +/- stopped controlling the grid when the popup opened, and + / - will no longer control the grid, even after the popup is closed.

A rare issue in my situation so I forget about it, but it happens. Maybe something can be done where when the ground tile popup is closed, +/- control goes back to the grid?

**Comment by gvissers** [comment]
Should be fixed.

**Comment by feeltheburn** [comment]
Yay, works, thx!

**Comment by feeltheburn** [comment]
I just noticed a problem that started since this. I hadn't actually used the ground tile popup since this change, just tested that the +/- worked.

Open the ground tile popup. Select a ground tile, use it on the map.

Right-clicking is supposed to let go of objects being used (ground, 2d, or 3d...)

Before this change, if there was a ground tile on your cursor, you could right-click and it would change to the water tile, then right-click again and it would be removed from the cursor. Odd behavior but no complaint about having to double-click.

Now though, if the ground tile popup is open, you can't let go of the tile. Right-click will turn it to water like before, but the water tile can't be right-clicked to be removed. 

The right-click will work after you click the corner X to close the ground tile popup.


So we seem to have lost "correct" right-click behavior with the popup open.

**Comment by gvissers** [comment]
Yeah, looks like the original intent was to close the tiles window on the first click (and change to water tile), then close on second click. That's something I missed when making the change.

Would you prefer to keep the tiles window open, or close it on the first click?

**Comment by feeltheburn** [comment]
Keeping it open seems more intuitive. If I'm using that, I'm probably using more than one tile.

Should work just like 3D objects in a perfect world, leave the popup alone, just get rid of whatever's attached to the cursor on right-click.

**Comment by gvissers** [comment]
I can't for the life of me figure out what the use of the two-click dance with the water tile is, so I have changed the code to let go of the selected tile on the first right click, and keep the window open.

**Comment by feeltheburn** [comment]
LOL, me neither. It never made sense to me, but considering how convoluted some of the interface is, I just accepted it. Wasn't that big a deal, heh.

Works, thx!
